kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-loki-stack
  namespace: monitoring
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      version: 1
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server
      version: 1
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-query
      version: 1